### ISSUE TITLE
app.js - component life cycle is defined but used it only for console.log

### ISSUE THREAD

**Issue by udaiyamnmGITHUB** [TCS-Research-Development/itunes-dom-ui-render#17]
this should be removed if we are not using to handle any events or needs to be commented as "future purpose"

**Comment by anish29292** [comment]
I have commented the other component life cycles for future use.

**Comment by udaiyamnmGITHUB** [comment]
this issue can be closed now.

**Comment by udaiyamnmGITHUB** [comment]
this issue can be closed now.
