### ISSUE TITLE
/getItunes API  - RESPONSE OBJECT SHOULD BE defined 

### ISSUE THREAD

**Issue by udaiyamnmGITHUB** [TCS-Research-Development/itunes-dom-ui-render#20]
success and failure response object is not constructed in API

**Comment by MANJUSHREEBR** [comment]
@udaiyamnmGITHUB,I have fixed this.

**Comment by udaiyamnmGITHUB** [comment]
@MANJUSHREEBR , 

yeah, I also reviewed the code. res body defined well
