### ISSUE TITLE
read.md file should have the detail of how to setup the proj and run the app

### ISSUE THREAD

**Issue by udaiyamnmGITHUB** [TCS-Research-Development/itunes-dom-ui-render#22]

**Comment by BangaruBabu** [comment]
@udaiyamnmGITHUB , 

Initially @MANJUSHREEBR designed README.md file  in the initial commit , later i completely modified all the content  . It would be good to ask someone(who is not in this project) to validate steps that we mentioned in README.md file . If they face any issues in executing steps , we can amend the steps .  Better ask them to perform these steps after committing **dev to master** . Any other comments accepted to refine the content 

README.md file :  [Link](https://github.com/TCS-Research-Development/itunes-dom-ui-render/blob/master/README.md)

**Comment by udaiyamnmGITHUB** [comment]
@BangaruBabu , 
yeah , sure. now the file is well explained with the steps to execute the app also. we will modify it is needed in the future.
