### ISSUE TITLE
UI - Album names are too lengthy and not as per the UI 

### ISSUE THREAD

**Issue by udaiyamnmGITHUB** [TCS-Research-Development/itunes-dom-ui-render#24]
UI - Album names are too lengthy and not as per the UI.
User may hovering the name and expect the name should be visible.
this is not a detailed req but we need to improvement.

**Comment by anish29292** [comment]
Tracknames that are lengthy have been truncated and will display the full name on hovering.

**Comment by udaiyamnmGITHUB** [comment]
it is tested and can be closed
