### ISSUE TITLE
UI - app.js  - remove the dead code

### ISSUE THREAD

**Issue by udaiyamnmGITHUB** [TCS-Research-Development/itunes-dom-ui-render#27]
newOne component is not part of the app , so remove all the dead code.

**Comment by anish29292** [comment]
@udaiyamnmGITHUB , Removed the component newOne(code snippet) from src/app.js (line 19 - 26) , hence closing this issue.. Can you please review and post feedback on it .

**Comment by udaiyamnmGITHUB** [comment]
done and all good , Thanks.
