### ISSUE TITLE
server.js , this logic in the getiTunes api  is not correct, refer the code snippet in the comment.

### ISSUE THREAD

**Issue by udaiyamnmGITHUB** [TCS-Research-Development/itunes-dom-ui-render#32]
if the result is undefined , it goes to the error block. not the info.

if (!result || result.length === 0) {
            var resObj = {status:"info", infoCode:"101", infoDesc:"No Records found"};
            res.json(resObj);
            res.end();
        }

**Comment by MANJUSHREEBR** [comment]
Hey,Uday I have removed it when you said..But I was getting error like result is undefined sometimes so again I have included.I will check out once and let you know.
